defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.16
webFolder: &webFolder
  at: web

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE.md
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json

version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: cd web && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: web
          <<: *whitelist

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: web

      - run:
          name: Lint TypeScript code
          command: cd web && yarn lint:all

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: web

      - run: cd web && yarn test:cover

      - persist_to_workspace:
          root: web
          <<: *whitelist

workflows:
  version: 2

  release:
    jobs:
      - checkout:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
      - lint:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - checkout
